### PR TITLE
Added option to always maintain aspect ratio

### PR DESCRIPTION
**Pull request by jaboon**
I added an option to always maintain the aspect ratio in the transforminteraction, defaults to false when option is not given

### CODE REVIEW

**Comment by Viglino** [comment]
Hello,
That's a good idea to let the user choices to keep aspect ration, but I thing the right way would be to add an [ol.events.condition](https://openlayers.org/en/latest/apidoc/ol.events.condition.html) parameter instead. The default param would be `ol.events.condition.shiftKeyOnly` but `ol.events.condition.always` would be use to always keep aspect ratio.
I'll try to see what I can do.
@+

**Comment by jaboon** [comment]
That sounds like a nicer way to do it indeed.
I'm not really experienced with OL yet and this fixed my issue so I thought I'd share it since you're maintaining the repo pretty well :)

**Comment by Viglino** [comment]
Anyway thanks for the feedback  :smirk:

**Comment by jaboon** [comment]
You're welcome, thanks for building and maintaining this nice library! :)

**Comment by Viglino** [comment]
Assez in the last commit.
Use `keepAspectRatio` option to `ol.events.condition.always` to allways keep aspect ratio.

**Comment by jaboon** [comment]
Works like a charm, thank you!

**Pull request closed without merging**
